---
  - name: tomcat | java installation
    yum: name={{ java_name }} state=present

  - name: tomcat | group add
    group: name={{ tomcat_os_group_name }}

  - name: tomcat | user add
    user: name={{ tomcat_os_user_name }} group={{ tomcat_os_group_name }} home={{ tomcat_home_path }} createhome=no
 
  - name: tomcat | binary download
    get_url: url={{ tomcat_binary_url }}  dest="{{ tomcat_dest }}{{ tomcat_binary }}"

  - name: tomcat | extract archive
    unarchive: src="{{ tomcat_dest }}{{ tomcat_binary }}" dest="{{ tomcat_dest }}" copy=no

  - name: tomcat | symlink install directory
    file: src="{{ tomcat_dest }}{{ tomcat_target_dir }}" path="{{ tomcat_dest }}{{ tomcat_symlink }}" state=link owner={{ tomcat_os_user_name }} group={{ tomcat_os_group_name }}

  - name: tomcat | change ownership of target installation
    file: path="{{ tomcat_dest }}{{ tomcat_target_dir }}" owner={{ tomcat_os_user_name }} group={{ tomcat_os_group_name }} state=directory recurse=yes

  - name: tomcat | installation of  start stop scripts
    template: 
     src="{{ item.src }}" dest="{{ item.dest }}" mode=0774 owner={{ tomcat_os_user_name }} group={{ tomcat_os_group_name }}
    with_items:
    - { src: 'tomcat_stop.j2', dest: '/opt/tomcat-latest/bin/tomcat_stop' }
    - { src: 'tomcat_start.j2', dest: '/opt/tomcat-latest/bin/tomcat_start' }

  - name: tomcat | start
    command: /opt/tomcat-latest/bin/tomcat_start
